import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'player.schema.dart';

///{@template Player}
/// Represents a player
///{@endtemplate}
@Model()
abstract class Player {
  /// The unique identifier of the player
  @PrimaryKey()
  String get id;

  /// The player's user name
  String get username;

  /// The player's email
  String get email;

  /// The display image set by the player
  String? get avatarUrl;

  /// The player's total score
  @Default('0')
  int get score;

  /// The number of times the player has won a game
  @Default('0')
  int get wins;

  /// The number of times the player has lost a match
  @Default('0')
  int get losses;

  /// The player's winning streak
  @Default('0')
  int get streak;

  /// The player's hashed password
  @Default('0')
  String get password;
}
