// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvMfzB1-IZCPRAY3aoa_y9nn3OhhM0Vn4',
    appId: '1:73844230479:android:864bcee2b52f4f3cff5d3a',
    messagingSenderId: '73844230479',
    projectId: 'battlefield-flutter',
    storageBucket: 'battlefield-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8aLDU3ZEzFdXtnui7zE2rFVQgn6Bl2Q',
    appId: '1:73844230479:ios:a874f4fadcae1e16ff5d3a',
    messagingSenderId: '73844230479',
    projectId: 'battlefield-flutter',
    storageBucket: 'battlefield-flutter.firebasestorage.app',
    iosBundleId: 'com.example.basic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI8aLDU3ZEzFdXtnui7zE2rFVQgn6Bl2Q',
    appId: '1:73844230479:ios:a874f4fadcae1e16ff5d3a',
    messagingSenderId: '73844230479',
    projectId: 'battlefield-flutter',
    storageBucket: 'battlefield-flutter.firebasestorage.app',
    iosBundleId: 'com.example.basic',
  );
}
